import type { GroovePreset, Preset, Ring } from "./rhythm";

export const RING_TEMPLATES: Ring[] = [
  {
    id: "kick",
    label: "Kick",
    division: 16,
    notes: [0, 4, 8, 12],
    phaseOffset: 0,
    voice: "kick",
    volume: 0.9,
    color: "#ff6b35",
  },
  {
    id: "snare",
    label: "Snare",
    division: 16,
    notes: [4, 12],
    phaseOffset: 0,
    voice: "snare",
    volume: 0.72,
    color: "#f7c948",
  },
  {
    id: "closed-hat",
    label: "Closed Hat",
    division: 16,
    notes: [0, 2, 4, 6, 8, 10, 12, 14],
    phaseOffset: 0,
    voice: "closedHat",
    volume: 0.42,
    color: "#6ee7b7",
  },
  {
    id: "open-hat",
    label: "Open Hat",
    division: 16,
    notes: [6, 14],
    phaseOffset: 0,
    voice: "openHat",
    volume: 0.38,
    color: "#60a5fa",
  },
  {
    id: "tom",
    label: "Tom",
    division: 12,
    notes: [3, 7, 11],
    phaseOffset: 0,
    voice: "tom",
    volume: 0.52,
    color: "#f472b6",
  },
];

export const DEFAULT_RINGS: Ring[] = RING_TEMPLATES.slice(0, 2);

export const PRESETS: Preset[] = [
  {
    id: "four-on-floor",
    name: "Four on Floor",
    category: "Basic",
    division: 16,
    notes: [0, 4, 8, 12],
  },
  {
    id: "backbeat",
    name: "Backbeat",
    category: "Basic",
    division: 16,
    notes: [4, 12],
  },
  {
    id: "eighths",
    name: "Eighth Notes",
    category: "Basic",
    division: 16,
    notes: [0, 2, 4, 6, 8, 10, 12, 14],
  },
  {
    id: "quarter-pulse",
    name: "Quarter Pulse",
    category: "Basic",
    division: 16,
    notes: [0, 4, 8, 12],
  },
  {
    id: "offbeat-eighths",
    name: "Offbeat Eighths",
    category: "Basic",
    division: 16,
    notes: [2, 6, 10, 14],
  },
  {
    id: "sixteenth-drive",
    name: "Sixteenth Drive",
    category: "Basic",
    division: 16,
    notes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
  },
  {
    id: "house-kick",
    name: "House Kick",
    category: "Dance",
    division: 16,
    notes: [0, 4, 8, 12],
  },
  {
    id: "disco-hats",
    name: "Disco Hats",
    category: "Dance",
    division: 16,
    notes: [2, 6, 10, 14],
  },
  {
    id: "garage-skip",
    name: "Garage Skip",
    category: "Dance",
    division: 16,
    notes: [0, 3, 7, 10, 12, 15],
  },
  {
    id: "breakbeat-snare",
    name: "Breakbeat Snare",
    category: "Dance",
    division: 16,
    notes: [4, 7, 12, 15],
  },
  {
    id: "techno-pulse",
    name: "Techno Pulse",
    category: "Dance",
    division: 16,
    notes: [0, 3, 4, 7, 8, 11, 12, 15],
  },
  {
    id: "clave",
    name: "Son Clave",
    category: "Latin",
    division: 16,
    notes: [0, 3, 6, 10, 12],
  },
  {
    id: "rumba-clave",
    name: "Rumba Clave",
    category: "Latin",
    division: 16,
    notes: [0, 3, 7, 10, 12],
  },
  {
    id: "bossa",
    name: "Bossa",
    category: "Latin",
    division: 16,
    notes: [0, 3, 6, 8, 11, 14],
  },
  {
    id: "tresillo",
    name: "Tresillo",
    category: "Latin",
    division: 16,
    notes: [0, 3, 6, 10, 13],
  },
  {
    id: "cumbia",
    name: "Cumbia",
    category: "Latin",
    division: 16,
    notes: [0, 3, 8, 11],
  },
  {
    id: "triplet-pulse",
    name: "Triplet Pulse",
    category: "Odd",
    division: 12,
    notes: [0, 4, 8],
  },
  {
    id: "odd-sparks",
    name: "Odd Sparks",
    category: "Odd",
    division: 7,
    notes: [0, 2, 5],
  },
  {
    id: "five-step",
    name: "Five Step",
    category: "Odd",
    division: 5,
    notes: [0, 2, 4],
  },
  {
    id: "seven-cycle",
    name: "Seven Cycle",
    category: "Odd",
    division: 7,
    notes: [0, 3, 5],
  },
  {
    id: "nine-pulse",
    name: "Nine Pulse",
    category: "Odd",
    division: 9,
    notes: [0, 2, 4, 6, 8],
  },
  {
    id: "twelve-triplets",
    name: "Twelve Triplets",
    category: "Odd",
    division: 12,
    notes: [0, 2, 4, 6, 8, 10],
  },
  {
    id: "pickup",
    name: "Pickup",
    category: "Fills",
    division: 16,
    notes: [14, 15],
  },
  {
    id: "half-bar-fill",
    name: "Half Bar Fill",
    category: "Fills",
    division: 16,
    notes: [8, 10, 12, 14, 15],
  },
  {
    id: "tom-run",
    name: "Tom Run",
    category: "Fills",
    division: 16,
    notes: [9, 10, 11, 12, 14, 15],
  },
  {
    id: "roll",
    name: "Roll",
    category: "Fills",
    division: 16,
    notes: [12, 13, 14, 15],
  },
  {
    id: "stutter",
    name: "Stutter",
    category: "Fills",
    division: 32,
    notes: [24, 26, 28, 29, 30, 31],
  },
];

export const GROOVE_PRESETS: GroovePreset[] = [
  {
    id: "straight-house",
    name: "Straight House",
    category: "Dance",
    rings: [
      { label: "Kick", division: 16, notes: [0, 4, 8, 12], voice: "kick", volume: 0.9 },
      { label: "Snare", division: 16, notes: [4, 12], voice: "snare", volume: 0.68 },
      { label: "Closed Hat", division: 16, notes: [2, 6, 10, 14], voice: "closedHat", volume: 0.42 },
      { label: "Open Hat", division: 16, notes: [6, 14], voice: "openHat", volume: 0.34 },
    ],
  },
  {
    id: "techno-drive",
    name: "Techno Drive",
    category: "Dance",
    rings: [
      { label: "Kick", division: 16, notes: [0, 4, 8, 12], voice: "kick", volume: 0.92 },
      { label: "Snare", division: 16, notes: [4, 12], voice: "snare", volume: 0.58 },
      { label: "Closed Hat", division: 16, notes: [1, 3, 5, 7, 9, 11, 13, 15], voice: "closedHat", volume: 0.36 },
      { label: "Tom", division: 16, notes: [7, 15], voice: "tom", volume: 0.42 },
    ],
  },
  {
    id: "uk-garage",
    name: "UK Garage",
    category: "Dance",
    rings: [
      { label: "Kick", division: 16, notes: [0, 7, 10], voice: "kick", volume: 0.86 },
      { label: "Snare", division: 16, notes: [4, 12, 15], voice: "snare", volume: 0.72 },
      { label: "Closed Hat", division: 16, notes: [2, 5, 8, 11, 14], voice: "closedHat", volume: 0.42 },
      { label: "Open Hat", division: 16, notes: [6, 13], voice: "openHat", volume: 0.34 },
    ],
  },
  {
    id: "funk-pocket",
    name: "Funk Pocket",
    category: "Funk",
    rings: [
      { label: "Kick", division: 16, notes: [0, 3, 6, 10, 13], voice: "kick", volume: 0.86 },
      { label: "Snare", division: 16, notes: [4, 12, 15], voice: "snare", volume: 0.74 },
      { label: "Closed Hat", division: 16, notes: [0, 2, 4, 6, 8, 10, 12, 14], voice: "closedHat", volume: 0.36 },
      { label: "Open Hat", division: 16, notes: [7], voice: "openHat", volume: 0.28 },
    ],
  },
  {
    id: "breakbeat",
    name: "Breakbeat",
    category: "Funk",
    rings: [
      { label: "Kick", division: 16, notes: [0, 3, 10, 14], voice: "kick", volume: 0.88 },
      { label: "Snare", division: 16, notes: [4, 7, 12, 15], voice: "snare", volume: 0.74 },
      { label: "Closed Hat", division: 16, notes: [0, 2, 5, 6, 8, 10, 13, 14], voice: "closedHat", volume: 0.38 },
    ],
  },
  {
    id: "bossa-kit",
    name: "Bossa Kit",
    category: "Latin",
    rings: [
      { label: "Kick", division: 16, notes: [0, 8, 11], voice: "kick", volume: 0.78 },
      { label: "Snare", division: 16, notes: [3, 6, 10, 14], voice: "snare", volume: 0.56 },
      { label: "Closed Hat", division: 16, notes: [0, 2, 4, 6, 8, 10, 12, 14], voice: "closedHat", volume: 0.34 },
      { label: "Tom", division: 16, notes: [0, 3, 6, 10, 12], voice: "tom", volume: 0.36 },
    ],
  },
  {
    id: "cumbia-kit",
    name: "Cumbia Kit",
    category: "Latin",
    rings: [
      { label: "Kick", division: 16, notes: [0, 3, 8, 11], voice: "kick", volume: 0.86 },
      { label: "Snare", division: 16, notes: [4, 12], voice: "snare", volume: 0.66 },
      { label: "Closed Hat", division: 16, notes: [0, 2, 4, 6, 8, 10, 12, 14], voice: "closedHat", volume: 0.34 },
      { label: "Tom", division: 16, notes: [6, 14], voice: "tom", volume: 0.4 },
    ],
  },
  {
    id: "seven-spiral",
    name: "Seven Spiral",
    category: "Odd",
    rings: [
      { label: "Kick", division: 7, notes: [0, 3, 5], voice: "kick", volume: 0.86 },
      { label: "Snare", division: 7, notes: [2, 6], voice: "snare", volume: 0.68 },
      { label: "Closed Hat", division: 14, notes: [0, 2, 4, 6, 8, 10, 12], voice: "closedHat", volume: 0.34 },
      { label: "Tom", division: 7, notes: [1, 4], voice: "tom", volume: 0.42 },
    ],
  },
  {
    id: "five-step-machine",
    name: "Five Step Machine",
    category: "Odd",
    rings: [
      { label: "Kick", division: 5, notes: [0, 2], voice: "kick", volume: 0.88 },
      { label: "Snare", division: 5, notes: [3], voice: "snare", volume: 0.68 },
      { label: "Closed Hat", division: 10, notes: [0, 2, 4, 6, 8], voice: "closedHat", volume: 0.36 },
      { label: "Open Hat", division: 10, notes: [5], voice: "openHat", volume: 0.3 },
    ],
  },
];
