import type { Preset, Ring } from "./rhythm";

export const RING_TEMPLATES: Ring[] = [
  {
    id: "kick",
    label: "Kick",
    division: 16,
    notes: [0, 4, 8, 12],
    voice: "kick",
    volume: 0.9,
    color: "#ff6b35",
  },
  {
    id: "snare",
    label: "Snare",
    division: 16,
    notes: [4, 12],
    voice: "snare",
    volume: 0.72,
    color: "#f7c948",
  },
  {
    id: "closed-hat",
    label: "Closed Hat",
    division: 16,
    notes: [0, 2, 4, 6, 8, 10, 12, 14],
    voice: "closedHat",
    volume: 0.42,
    color: "#6ee7b7",
  },
  {
    id: "open-hat",
    label: "Open Hat",
    division: 16,
    notes: [6, 14],
    voice: "openHat",
    volume: 0.38,
    color: "#60a5fa",
  },
  {
    id: "tom",
    label: "Tom",
    division: 12,
    notes: [3, 7, 11],
    voice: "tom",
    volume: 0.52,
    color: "#f472b6",
  },
];

export const DEFAULT_RINGS: Ring[] = RING_TEMPLATES.slice(0, 2);

export const PRESETS: Preset[] = [
  {
    id: "four-on-floor",
    name: "Four on Floor",
    category: "Basic",
    division: 16,
    notes: [0, 4, 8, 12],
  },
  {
    id: "backbeat",
    name: "Backbeat",
    category: "Basic",
    division: 16,
    notes: [4, 12],
  },
  {
    id: "eighths",
    name: "Eighth Notes",
    category: "Basic",
    division: 16,
    notes: [0, 2, 4, 6, 8, 10, 12, 14],
  },
  {
    id: "quarter-pulse",
    name: "Quarter Pulse",
    category: "Basic",
    division: 16,
    notes: [0, 4, 8, 12],
  },
  {
    id: "offbeat-eighths",
    name: "Offbeat Eighths",
    category: "Basic",
    division: 16,
    notes: [2, 6, 10, 14],
  },
  {
    id: "sixteenth-drive",
    name: "Sixteenth Drive",
    category: "Basic",
    division: 16,
    notes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
  },
  {
    id: "house-kick",
    name: "House Kick",
    category: "Dance",
    division: 16,
    notes: [0, 4, 8, 12],
  },
  {
    id: "disco-hats",
    name: "Disco Hats",
    category: "Dance",
    division: 16,
    notes: [2, 6, 10, 14],
  },
  {
    id: "garage-skip",
    name: "Garage Skip",
    category: "Dance",
    division: 16,
    notes: [0, 3, 7, 10, 12, 15],
  },
  {
    id: "breakbeat-snare",
    name: "Breakbeat Snare",
    category: "Dance",
    division: 16,
    notes: [4, 7, 12, 15],
  },
  {
    id: "techno-pulse",
    name: "Techno Pulse",
    category: "Dance",
    division: 16,
    notes: [0, 3, 4, 7, 8, 11, 12, 15],
  },
  {
    id: "clave",
    name: "Son Clave",
    category: "Latin",
    division: 16,
    notes: [0, 3, 6, 10, 12],
  },
  {
    id: "rumba-clave",
    name: "Rumba Clave",
    category: "Latin",
    division: 16,
    notes: [0, 3, 7, 10, 12],
  },
  {
    id: "bossa",
    name: "Bossa",
    category: "Latin",
    division: 16,
    notes: [0, 3, 6, 8, 11, 14],
  },
  {
    id: "tresillo",
    name: "Tresillo",
    category: "Latin",
    division: 16,
    notes: [0, 3, 6, 10, 13],
  },
  {
    id: "cumbia",
    name: "Cumbia",
    category: "Latin",
    division: 16,
    notes: [0, 3, 8, 11],
  },
  {
    id: "triplet-pulse",
    name: "Triplet Pulse",
    category: "Odd",
    division: 12,
    notes: [0, 4, 8],
  },
  {
    id: "odd-sparks",
    name: "Odd Sparks",
    category: "Odd",
    division: 7,
    notes: [0, 2, 5],
  },
  {
    id: "five-step",
    name: "Five Step",
    category: "Odd",
    division: 5,
    notes: [0, 2, 4],
  },
  {
    id: "seven-cycle",
    name: "Seven Cycle",
    category: "Odd",
    division: 7,
    notes: [0, 3, 5],
  },
  {
    id: "nine-pulse",
    name: "Nine Pulse",
    category: "Odd",
    division: 9,
    notes: [0, 2, 4, 6, 8],
  },
  {
    id: "twelve-triplets",
    name: "Twelve Triplets",
    category: "Odd",
    division: 12,
    notes: [0, 2, 4, 6, 8, 10],
  },
  {
    id: "pickup",
    name: "Pickup",
    category: "Fills",
    division: 16,
    notes: [14, 15],
  },
  {
    id: "half-bar-fill",
    name: "Half Bar Fill",
    category: "Fills",
    division: 16,
    notes: [8, 10, 12, 14, 15],
  },
  {
    id: "tom-run",
    name: "Tom Run",
    category: "Fills",
    division: 16,
    notes: [9, 10, 11, 12, 14, 15],
  },
  {
    id: "roll",
    name: "Roll",
    category: "Fills",
    division: 16,
    notes: [12, 13, 14, 15],
  },
  {
    id: "stutter",
    name: "Stutter",
    category: "Fills",
    division: 32,
    notes: [24, 26, 28, 29, 30, 31],
  },
];
